log_type all
listener 8883

tls_version tlsv1.2
allow_anonymous false
require_certificate false

cafile /opt/homebrew/etc/mosquitto/certificates/rootCA.pem
certfile /opt/homebrew/etc/mosquitto/certificates/broker.pem
keyfile /opt/homebrew/etc/mosquitto/certificates/broker-key.pem

acl_file /opt/homebrew/etc/mosquitto/acl.conf
password_file /opt/homebrew/etc/mosquitto/passwords/passwords_file